export const FLOATING_TEXTS = [
  "UI/UX Design",
  "User Experience",
  "User Interface",
  "Wireframing",
  "Prototyping",
  "Figma",
  "Adobe XD",
  "Sketch",
  "User Research",
  "Web Development",
  "React",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "HTML5",
  "CSS3",
  "Responsive Design",
  "Frontend",
  "Backend",
  "Full Stack",
  "API REST",
  "GraphQL",
  "Web Performance",
  "Mobile Apps",
  "React Native",
  "Flutter",
  "iOS",
  "Android",
  "Cross-platform",
  "Native Development",
  "Software Engineering",
  "Clean Code",
  "Architecture",
  "DevOps",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Docker",
  "Kubernetes",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Social Media",
  "Content Marketing",
  "Branding",
  "Analytics",
  "Conversion Rate",
  "Growth Hacking",
  "Creative Solutions",
  "Innovation",
  "Problem Solving",
  "Agile",
  "Scrum",
  "Project Management",
  "Team Collaboration",
] as const;
